### ISSUE TITLE
Update new_enemyAI branch from Master

### ISSUE THREAD

**Issue by ghost** [Ben-Healey/Neon_Game#25]
Trying to update my new_enemyAI branch with the new Master branch level gives 2100+ changes to review in the merge diff list, so something is gonna need to be done to combine them. Any ideas?

**Comment by ghost** [comment]
Pulling scripts from new_enemyAI branch and manually re-adding scripts and enemy entities into updated main branch with combat room redesigned and built by @Ben-Healey - commit coming soon.

**Comment by Ben-Healey** [comment]
Not longer needed
